version: '3'
services:
  goapp:
    build:
      context: . 
      dockerfile: Dockerfile
    environment:      
      GOAPP_PORT: 8080
      MONGO_URL: mongodb
      MONGO_COLLECTION: user
      MONGO_DB: test
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest    
    ports:
      - 27017:27017  
