version: '3'
services:
  goapp_with_test:
    build:
      context: . 
      dockerfile: Dockerfile-test
    environment:      
      GOAPP_PORT: 8080
      MONGO_URL: mongodb
      MONGO_COLLECTION: user
      MONGO_DB: test
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    command: >
        bash -c "dockerize -wait tcp://mongodb:27017 -timeout 30s &&        
                 go test -v"
  mongodb:
    image: mongo:latest    
    ports:
      - 27017:27017  
