FROM golang:latest 

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN mkdir /app
ENV GOPATH /app

RUN go get -u gopkg.in/mgo.v2
RUN go get -u github.com/gin-gonic/gin 
RUN go get -u gopkg.in/check.v1
RUN go get -u github.com/vjeantet/jodaTime
RUN go get -u github.com/swaggo/gin-swagger
RUN go get -u github.com/swaggo/gin-swagger/swaggerFiles

ADD ./src /app/src
WORKDIR /app/src 
RUN go build -o goapp .

EXPOSE 8080 
CMD ["./goapp"]
